const dummyData = [
    {
      id: 1,
      name: 'John Doe',
      gender: 'Male',
      placeOfBirth: 'New York',
      city: 'New York',
      idCardNumber: '1234567890',
      headline: 'Software Engineer',
      phone: '123-456-7890',
      address: '123 Main St, New York, NY',
      invoice: 'https://example.com/invoice1.pdf',
    },
    {
      id: 2,
      name: 'Jane Smith',
      gender: 'Female',
      placeOfBirth: 'Los Angeles',
      city: 'Los Angeles',
      idCardNumber: '0987654321',
      headline: 'Product Manager',
      phone: '098-765-4321',
      address: '456 Elm St, Los Angeles, CA',
      invoice: 'https://example.com/invoice2.pdf',
    },
    {
      id: 3,
      name: 'Alice Johnson',
      gender: 'Female',
      placeOfBirth: 'Chicago',
      city: 'Chicago',
      idCardNumber: '1122334455',
      headline: 'UX Designer',
      phone: '321-654-9870',
      address: '789 Oak St, Chicago, IL',
      invoice: 'https://example.com/invoice3.pdf',
    },
    {
      id: 4,
      name: 'Bob Brown',
      gender: 'Male',
      placeOfBirth: 'San Francisco',
      city: 'San Francisco',
      idCardNumber: '2233445566',
      headline: 'Data Scientist',
      phone: '654-321-0987',
      address: '101 Pine St, San Francisco, CA',
      invoice: 'https://example.com/invoice4.pdf',
    },
    {
      id: 5,
      name: 'Charlie Davis',
      gender: 'Male',
      placeOfBirth: 'Seattle',
      city: 'Seattle',
      idCardNumber: '3344556677',
      headline: 'Web Developer',
      phone: '987-654-3210',
      address: '202 Cedar St, Seattle, WA',
      invoice: 'https://example.com/invoice5.pdf',
    },
    {
      id: 6,
      name: 'Emily Wilson',
      gender: 'Female',
      placeOfBirth: 'Boston',
      city: 'Boston',
      idCardNumber: '4455667788',
      headline: 'Marketing Specialist',
      phone: '876-543-2109',
      address: '303 Maple St, Boston, MA',
      invoice: 'https://example.com/invoice6.pdf',
    },
    {
      id: 7,
      name: 'David Lee',
      gender: 'Male',
      placeOfBirth: 'Austin',
      city: 'Austin',
      idCardNumber: '5566778899',
      headline: 'Systems Analyst',
      phone: '765-432-1098',
      address: '404 Elm St, Austin, TX',
      invoice: 'https://example.com/invoice7.pdf',
    },
    {
      id: 8,
      name: 'Sophia Martinez',
      gender: 'Female',
      placeOfBirth: 'Miami',
      city: 'Miami',
      idCardNumber: '6677889900',
      headline: 'Product Designer',
      phone: '654-321-0987',
      address: '505 Birch St, Miami, FL',
      invoice: 'https://example.com/invoice8.pdf',
    },
    {
      id: 9,
      name: 'Michael Thomas',
      gender: 'Male',
      placeOfBirth: 'Philadelphia',
      city: 'Philadelphia',
      idCardNumber: '7788990011',
      headline: 'IT Consultant',
      phone: '543-210-9876',
      address: '606 Pine St, Philadelphia, PA',
      invoice: 'https://example.com/invoice9.pdf',
    },
    {
      id: 10,
      name: 'Olivia Garcia',
      gender: 'Female',
      placeOfBirth: 'Denver',
      city: 'Denver',
      idCardNumber: '8899001122',
      headline: 'Business Analyst',
      phone: '432-109-8765',
      address: '707 Spruce St, Denver, CO',
      invoice: 'https://example.com/invoice10.pdf',
    },
    {
      id: 11,
      name: 'James Wilson',
      gender: 'Male',
      placeOfBirth: 'Orlando',
      city: 'Orlando',
      idCardNumber: '9900112233',
      headline: 'Network Engineer',
      phone: '321-098-7654',
      address: '808 Fir St, Orlando, FL',
      invoice: 'https://example.com/invoice11.pdf',
    },
    {
      id: 12,
      name: 'Isabella Lee',
      gender: 'Female',
      placeOfBirth: 'San Diego',
      city: 'San Diego',
      idCardNumber: '0011223344',
      headline: 'Software Architect',
      phone: '210-987-6543',
      address: '909 Willow St, San Diego, CA',
      invoice: 'https://example.com/invoice12.pdf',
    },
  ];
  